---
title: "Read Txdot Collision Data"
author: "Alan Jackson"
date: "February 26, 2018"
output: html_document
---

```{r setup, include=FALSE}
library(tidyverse)
library(lubridate)
library(sf)

googlecrs <- 4326

#   Crash Severity ID table
Severity <- c(
"0",	"UNKNOWN", 
"1",	"SUSPECTED SERIOUS INJURY",
"2",	"NON-INCAPACITATING",
"3",	"POSSIBLE INJURY",
"4",	"FATAL",
"5",	"NOT INJURED",
"94",	"REPORTED INVALID",
"95",	"NOT REPORTED"
)
Severity <- cbind.data.frame(split(Severity, rep(1:2, times=length(Severity)/2)), stringsAsFactors=F)
names(Severity) <- c("Crash_Sev_ID", "Severity")
Severity$Crash_Sev_ID <- as.integer(Severity$Crash_Sev_ID)

#   Crash Harm ID table
Harm <- c(
"1",	"Pedestrian", 
"2",	"Motor Vehicle in Transport",
"3",	"Rail Road",
"4",	"Parked Car",
"5",	"Pedal Cyclist",
"6",	"Animal",
"7",	"Fixed Object",
"8",	"Other Object",
"9",	"Other Non-Collision",
"10",	"Overturned",
"11",	"Not Reported",
"93",	"Undetermined",
"94",	"Reported Invalid"
)
Harm <- cbind.data.frame(split(Harm, rep(1:2, times=length(Harm)/2)), stringsAsFactors=F)
names(Harm) <- c("Harm_Evnt_ID", "Harmed")
Harm$Harm_Evnt_ID <- as.integer(Harm$Harm_Evnt_ID)


HarrisBoundary <- c(-95.990842, 29.499559, -94.852384, 30.180927)

City <- c(
 "29", "Baytown",
 "30", "Beaumont",
 "33", "Bellaire",
 "57", "Bunker Hill Village",
 "111", "Deer Park",
 "135", "El Lago",
 "160", "Friendswood",
 "164", "Galena Park",
 "208", "Houston",
 "211", "Humble",
 "212", "Hunters Creek Village",
 "219", "Jacinto City",
 "223", "Jersey Village",
 "228", "Katy",
"244", "La Porte",
"255", "League City",
"260", "Liberty",
"296", "Missouri City",
"304", "Nassau Bay",
"325", "Pasadena",
"326", "Pearland",
"333", "Piney Point Village",
"359", "Richmond",
"383", "San Marcos",
"391", "Seabrook",
"405", "South Houston",
"408", "Spring Valley",
"409", "Stafford",
"422", "Taylor Lake Village",
"430", "Tomball",
"434", "Tyler",
"447", "Webster",
"453", "West University Place",
"478", "Aldine",
"625", "Channelview",
"647", "Cloverleaf",
"672", "Crosby",
"843", "Hedwig Village",
"851", "Highlands",
"855", "Hilshire Village",
"1061", "Mission Bend",
"1073", "Morgans Point",
"1326", "Shoreacres",
"1348", "Southside Place",
"1353", "Spring",
"1444", "Waller",
"1535", "Kingwood",
"1585", "Rural Brazoria County",
"1601", "Rural Chambers County",
"1644", "Rural Fort Bend County",
"1649", "Rural Galveston County",
"1665", "Rural Hardin County",
"1666", "Rural Harris County",
"1667", "Rural Harrison County",
"1668", "Rural Hartley County",
"1678", "Rural Houston County",
"1711", "Rural Liberty County",
"1719", "Rural Madison County",
"1735", "Rural Montgomery County",
"1926", "Alief",
"2071", "Atascosita",
"3313", "Cypress",
"4728", "Huffman",
"5659", "Meadows Place",
"6756", "Porter"
)
City <- cbind.data.frame(split(City, rep(1:2, times=length(City)/2)), stringsAsFactors=F)
names(City) <- c("Rpt_City_ID", "City")
City$Rpt_City_ID <- as.integer(City$Rpt_City_ID)

knitr::opts_chunk$set(echo = TRUE)
```



```{r Read files}
filenames <- list.files(path = "~/Rprojects/Collisions/TrafficAccidents", pattern="*csv$")

filenames <- paste("TrafficAccidents/",filenames, sep="")

DF <- read.csv(filenames[1], stringsAsFactors = FALSE)

for (i in filenames[-1]) {
  df <- read.csv(i, stringsAsFactors = FALSE)
  DF <- rbind(DF, df)
}

df <- DF %>% select(Crash_Fatal_Fl, Crash_Date,	Crash_Time, Rpt_City_ID, Rpt_Block_Num, Rpt_Street_Pfx,	Rpt_Street_Name, Rpt_Street_Sfx, At_Intrsct_Fl, Latitude, Longitude, Street_Name, Street_Nbr, Tot_Injry_Cnt, Death_Cnt, Crash_Sev_ID, Crash_Speed_Limit, Harm_Evnt_ID)

df <- left_join(df, City, by="Rpt_City_ID")
df <- left_join(df, Severity, by="Crash_Sev_ID")
df <- left_join(df, Harm, by="Harm_Evnt_ID")



```


Do some quality control checks


```{r Look for nulls}

# Look for NA's in the various fields

df %>%
    map_df(function(x) sum(is.na(x))) %>%
    gather(feature, num_nulls) %>%
    print(n = 100)

```

```{r Look at Crash_Fatal_Fl}

sort(unique(df$Crash_Fatal_Fl))

```

```{r Look at Crash_Date}

sort(unique(df$Crash_Date))

df$Crash_DateTime <- mdy_hm(paste(df$Crash_Date, df$Crash_Time))

#  make it a date

df$Crash_Date <- mdy(df$Crash_Date)

range(df$Crash_Date)

```

```{r Look at Crash_Time}

sort(unique(df$Crash_Time))

#   make it a time

df$Crash_Time <- ymd_hm(paste("2000/1/1",df$Crash_Time))
sort(unique(hour(df$Crash_Time)))

```

```{r Look at City ID}

sort(unique(df$Rpt_City_ID))

```

```{r Look at Rpt_Blk_Num}

sort(unique(df$Rpt_Block_Num))

df$Rpt_Block_Num[grepl("\\D+", df$Rpt_Block_Num)]

#   Remove non-numeric stuff

df$Rpt_Block_Num <- str_replace(df$Rpt_Block_Num, " BLOCK","")
df$Rpt_Block_Num <- str_replace_all(df$Rpt_Block_Num, "O","0")
df$Rpt_Block_Num <- str_replace_all(df$Rpt_Block_Num, "^\\d+-","")
df$Rpt_Block_Num <- str_replace_all(df$Rpt_Block_Num, "PP","00")
df$Rpt_Block_Num <- str_replace_all(df$Rpt_Block_Num, " 1/2","")
df$Rpt_Block_Num <- str_replace(df$Rpt_Block_Num, "\\D+","")
df$Rpt_Block_Num <- str_replace(df$Rpt_Block_Num, "0RE","")

sort(unique(df$Rpt_Block_Num))
```

```{r Look at Rpr_Street_Pfx}

sort(unique(df$Rpt_Street_Pfx))

df$Rpt_Street_Pfx <- str_replace(df$Rpt_Street_Pfx, "UNK", "")
```
```{r Look at Rpt_Street_Sfx}

sort(unique(df$Rpt_Street_Sfx))

```

```{r Look at Latitude and Longitude}

df$Latitude[grepl("[^0-9\\-\\. ]", df$Latitude)]
df$Longitude[grepl("[^-][^0-9\\. ]", df$Longitude)]
df$Latitude <- as.numeric(df$Latitude)
df$Longitude <- as.numeric(df$Longitude)
range(df$Latitude, na.rm=TRUE)
range(df$Longitude, na.rm = TRUE)

```
```{r Look at Street_Nbr}

sort(unique(df$Street_Nbr))
df$Street_Nbr[grepl("\\D+", df$Street_Nbr)]
df$Street_Nbr <- str_replace(df$Street_Nbr, "\\D+","")

```


```{r Look at Tot_Injry_Cnt}

sort(unique(df$Tot_Injry_Cnt))

```
```{r Look at Death_Cnt}

sort(unique(df$Death_Cnt))

```

```{r Look at Severity}

sort(unique(df$Severity))

df %>% group_by(Severity) %>% 
  summarise(count=n()) %>%
  arrange(count)

```


```{r Look at Harmed}

sort(unique(df$Harmed))

df %>% group_by(Harmed) %>% 
  summarise(count=n()) %>%
  arrange(count)

```




```{r Look at Rpt_Street_Name}

sort(unique(df$Rpt_Street_Name))
```

```{r Look at Street_Name}

sort(unique((df$Street_Name)))

keepdf <-  df
```

#     Add neighborhood and zipcode designations to records

```{r Add neighborhood and zipcode}
####   mask out rows with bad coordinates
maskcoord <- !(is.na(df$Latitude) | is.na(df$Longitude))
#  Create a temporary sf data frame for doing the intersects
# set longitudes as the first column and latitudes as the second
dat <- data.frame(Longitude=df$Longitude[maskcoord], Latitude=df$Latitude[maskcoord], stringsAsFactors = FALSE)

dat <- st_as_sf(dat, coords=c("Longitude", "Latitude"), crs=googlecrs, agr = "identity")
# read in neighborhood and zipcode polygons
neighborhoods <- readRDS("~/Dropbox/CrimeStats/NeighborhoodPolys.rds")
zipcodes <- readRDS("~/Dropbox/CrimeStats/ZipCodes.rds")

# st_intersects to see if points are inside poly
#  This is a matrix of T/F values, npoints x npolys in size
#  if a point is in multiple polys it will show up here
a <- st_intersects(dat, neighborhoods, sparse = FALSE)
max(rowSums(a)) # this is the maximum number of polys for some point
hist(rowSums(a))# just curious how they are distributed.
#   collect all the neighborhoods a point falls into, separate by
#   commas, and put into the Nbhd field
diddle <- function (i) {paste(neighborhoods$Name[i], collapse=', ')}
df$Nbhd[maskcoord] <-  apply(a,1,diddle)  #  work on "a" row-wise

######################################
#########   add zipcode
######################################
#   find points in polygons
#   since zipcodes don't overlap, let's just grab the array index
#   instead of creating a huge matrix
a <- st_intersects(dat, zipcodes, sparse = TRUE)

#   Append the ZIP field to the data frame
df$Zip_Code[maskcoord] <- zipcodes$Zip_Code[unlist(a)]


```


```{r save result out to a file}

saveRDS(df, file="~/Rprojects/Collisions/Collisions_2010_2017.rds")
```

